### ISSUE TITLE
Building ottr on publichealth hub fails

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3263]
### Bug description

```
Step 26/34 : RUN r /tmp/r-packages/ph-142.r
 ---> Running in 61d43c2a196e
[1] "Installing packages for PH142"
[1] "Installing ottr..."
Downloading GitHub repo ucbds-infra/ottr@0.1.0

* checking for file ‘/tmp/remotes6300954ab/ucbds-infra-ottr-02ccf00/DESCRIPTION’ ... OK
* preparing ‘ottr’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘ottr_0.1.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘ottr’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ottr)
Error in `action()`:
! `class` is absent but must be supplied.
Backtrace:
     ▆
  1. ├─base `<fn>`("/tmp/r-packages/ph-142.r", print.eval = FALSE)
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. └─devtools::install_github(...) at tmp/r-packages/ph-142.r:29:0
  6.   └─rlang `<fn>`() at tmp/r-packages/ph-142.r:29:0
  7.     └─rlang:::check_dots(env, error, action, call)
  8.       └─rlang:::action_dots(...)
  9.         ├─base try_dots(...)
 10.         └─rlang action(...)
 11.           └─rlang:::validate_signal_args(.subclass)
 12.             └─rlang::check_required(class, call = env)
 13.               └─rlang::abort(msg, call = call)
Removing intermediate container 61d43c2a196e
The command '/bin/sh -c r /tmp/r-packages/ph-142.r' returned a non-zero code: 1Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy", line 8, in <module>
    sys.exit(main())
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 122, in main
    image.build(not args.no_cache)
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/config.py", line 160, in build
    self.r2d.build()
  File "/root/repo/venv/lib/python3.7/site-packages/repo2docker/app.py", line 812, in build
    raise BuildError(l["error"])
repo2docker.engine.BuildError: The command '/bin/sh -c r /tmp/r-packages/ph-142.r' returned a non-zero code: 1

Exited with code exit status 1

CircleCI received exit code 1
```

### Environment & setup

- Hub: publichealth

### How to reproduce

Force publichealth to rebuild ottr.

**Comment by felder** [comment]
Looks exactly like #3216

**Comment by felder** [comment]
Looks reasonable in staging:

```
> library(ottr)
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ottr_0.1.0

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2   

>
```

**Comment by felder** [comment]
Deployed to prod.
