### ISSUE TITLE
Getting 403s from github for unauthenticated requests

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3341]
```
#!/bin/bash -eo pipefail
# CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
COMMIT_RANGE=$(./.circleci/get-commit-range.py)
echo ${COMMIT_RANGE}
echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}

Traceback (most recent call last):
  File "./.circleci/get-commit-range.py", line 89, in <module>
    main()
  File "./.circleci/get-commit-range.py", line 81, in main
    print(from_pr(args.project, args.repo, pr_number))
  File "./.circleci/get-commit-range.py", line 10, in from_pr
    pr = gh.get_repo(f'{project}/{repo}').get_pull(pr_number)
  File "/root/repo/venv/lib/python3.7/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/root/repo/venv/lib/python3.7/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/root/repo/venv/lib/python3.7/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 18.207.110.22. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Exited with code exit status 1

CircleCI received exit code 1

```

**Comment by felder** [comment]
Julia did it too.

https://app.circleci.com/pipelines/github/berkeley-dsep-infra/datahub/1205/workflows/9cd40227-4287-44cb-aa88-ee9cfcf9fc4e/jobs/10400/parallel-runs/0/steps/0-105

I thought this was fixed or at least we haven't seen it for a while.

**Comment by balajialg** [comment]
@yuvipanda @ryanlovett Any idea why the GitHub unauthenticated issue is recurring considering the corrective action taken as part of issue #1048?

**Comment by yuvipanda** [comment]
It's determined mostly by how many other CircleCI jobs are running on the node with same IP. We were exhausting it quite frequently before the move to packagemanager.rstudio.com, but I think it'll happen less frequently now. Restarting after an hour or so should mostly 'fix' it.

Using an auth token would definitely be a more long term fix.

**Comment by balajialg** [comment]
Got it, Thanks @yuvipanda!

@felder Should we close this issue considering Yuvi's response? Let me know if there are other solutions you are anticipating currently.

**Comment by felder** [comment]
@balajialg sure!
