### ISSUE TITLE
node-placeholder-scaler is reporting errors for the description for "evening cool off" on the datahub scaling events calendar

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#4157]
### Bug description

```
MacBook-Pro:node-placeholder felder$ kubectl get pods -n node-placeholder | grep scaler
node-placeholder-node-placeholder-scaler-59d9847684-889gh   1/1     Running   0          14d

MacBook-Pro:node-placeholder felder$ kubectl logs -n node-placeholder node-placeholder-node-placeholder-scaler-59d9847684-889gh | more
2023-01-22 04:29:43,304 deployment.apps/dlab-placeholder configured
2023-01-22 04:29:43,305 Setting eecs to have 1 replicas
2023-01-22 04:29:43,654 deployment.apps/eecs-placeholder configured
2023-01-22 04:29:43,655 Setting ischool to have 1 replicas
2023-01-22 04:29:43,982 deployment.apps/ischool-placeholder configured
2023-01-22 04:29:43,983 Setting publichealth to have 1 replicas
2023-01-22 04:29:44,323 deployment.apps/publichealth-placeholder configured
2023-01-22 04:29:44,324 Setting r to have 1 replicas
2023-01-22 04:29:44,641 deployment.apps/r-placeholder configured
2023-01-22 04:29:44,642 Setting small-courses to have 1 replicas
2023-01-22 04:29:44,991 deployment.apps/small-courses-placeholder configured
2023-01-22 04:29:44,992 Setting stat159 to have 1 replicas
2023-01-22 04:29:45,330 deployment.apps/stat159-placeholder configured
2023-01-22 04:29:45,331 Setting stat20 to have 1 replicas
2023-01-22 04:29:45,659 deployment.apps/stat20-placeholder configured
2023-01-22 04:29:45,764 Posted annotation to Grafana
2023-01-22 04:30:46,250 Found event Evening Cool Off 2023-01-21 20:00 PST to 2023-01-22 08:00 PST
2023-01-22 04:30:46,251 Error in parsing description of Evening Cool Off 2023-01-21 20:00 PST to 2023-01-22 08:00 PST
2023-01-22 04:30:46,251 ev.description='a11y: 0<br />astro: 0<br />biology: 0<br />cee: 0<br />data100: 0<br />data101: 0<br />data102: 0<br />data8: 0<br />datahub: 0<br />dlab: 0<br />eecs: 0<br />ischool: 0<br />prob140: 0<br />publichealth: 0<br />r: 0<br />small-courses: 0<br />stat159: 0<br />'
2023-01-22 04:30:46,251 No description in event Evening Cool Off 2023-01-21 20:00 PST to 2023-01-22 08:00 PST
```

### Environment & setup

- Hub: 
- Language:

**Comment by ryanlovett** [comment]
This happened before once. I think I slacked the solution of copy/pasting the description into an editor with no style support, then copy/pasting back. Edit: actually I think I just clicked the "remove style" button in the description editor.

When I look at the logs I see:
```
$ k -n node-placeholder logs node-placeholder-node-placeholder-scaler-59d9847684-889gh
2023-01-24 01:02:05,908 Found event PS3: Monday 2023-01-23 16:30 PST to 18:30 PST
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/scaler/__main__.py", line 5, in <module>
    main()
  File "/srv/scaler/scaler.py", line 97, in main
    replica_count_overrides = get_replica_counts(get_events(config["calendarUrl"]))
  File "/srv/scaler/scaler.py", line 69, in get_replica_counts
    for pool_name, count in pools_replica_config.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by ryanlovett** [comment]
I'm augmenting scalar.py to detect this and fail gracefully. A reasonable fix might be to simply `ev.description.replace('<br />', '\n')`.

**Comment by ryanlovett** [comment]
After the pod was restarted during CI deploy, both errors above are gone.

```bash
$ k -n node-placeholder -l app.kubernetes.io/instance=node-placeholder logs
```

**Comment by felder** [comment]
@ryanlovett one thing to note is that this issue will only occur during the cooldown event.  So we won't know for sure if it worked until then.

**Comment by felder** [comment]
@ryanlovett one thing to also note is that stat20 has scheduled events which overlap with existing ones.

It's unclear to me how the tool deals with multiple events scheduled at the same time and even more so how it deals with multiple events scheduled at the same time for the same pool.

**Comment by ryanlovett** [comment]
@felder Re: cooldown, are you sure? I think the code that generates "[Error in parsing](https://github.com/berkeley-dsep-infra/datahub/blob/staging/images/node-placeholder-scaler/scaler/scaler.py#L62)" happens [each loop](https://github.com/berkeley-dsep-infra/datahub/blob/staging/images/node-placeholder-scaler/scaler/scaler.py#L102).

**Comment by ryanlovett** [comment]
@felder I remove stat20 from the main cooldown when I created its events a week or two ago. However the PS3 event has an overlap.

**Comment by felder** [comment]
@ryanlovett I'm not 100% sure, but I believe the way it works is every second it asks google calendar for events that match with the current time and then parses them.

**Comment by felder** [comment]
If you add an event it doesn't like, it won't crash or error on it until its scheduled time.

**Comment by felder** [comment]
This is interesting too

```
2023-01-24 01:59:13,335 Found event PS3: Monday 2023-01-23 16:30 PST to 18:30 PST
2023-01-24 01:59:13,335 Event description not parsed as dictionary.
2023-01-24 01:59:13,335 ev.description='r:3'
2023-01-24 01:59:13,336 Found event PS3: Monday 2023-01-23 16:00 PST to 18:30 PST
2023-01-24 01:59:13,336 Overrides: {'r': 3}
```

In this case, the event was modified in google calendar and it's a repeating event.  It's picking up both even though only one is visible.

**Comment by balajialg** [comment]
- [ ] Issue to be created for handling exceptions from calendar based autoscaler!
- [ ] Explore middleware to format calendar entires?
