### ISSUE TITLE
Request my old files stored in Datahub - I have the rest , other than my R course PHW251 2022

### ISSUE THREAD

**Issue by mnazneen** [berkeley-dsep-infra/hubs#5960]
### Your UC Berkeley Email Address

moyrarasheed39@berkeley.edu

### Link to Your Datahub Folder

Your publichealth files have been archived due to inactivity.

If you want to retrieve a copy of your files through email, please open a Data Archival Request via GitHub using the custom URL below:

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub&link=gs://ucb-datahub-archived-homedirs/2023-3-fall/publichealth/moyrarasheed39.tar.gz

After submitting the form, a Datahub admin will send you a signed link to download your publichealth files via email within a few days.
This is what I have in where are my files.

**Comment by balajialg** [comment]
@mnazneen I just sent you the files archived in Public Health Hub. I couldn't find any files in https://datahub.berkeley.edu/ and https://r.datahub.berkeley.edu/. I need a link from the file "WHERE-ARE-MY-FILES.txt" left in your home directory from the hubs you actually used. The following example is the link we need from"WHERE-ARE-MY-FILES.txt" when you log into the hub and it you should include it as part of this request. 

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/USER_ID.tar.gz

We cannot service this request without this information.

**Comment by mnazneen** [comment]
I cant retrieve WHERE-ARE-MY-FILES.txt"because when I try to open datahub for my r course, I cant open data hub at all. 



"This is the message I get:Traceback (most recent call last):
File "/srv/conda/lib/python3.10/site-packages/nbgitpuller/pull.py", line 118, in resolve_default_branch
    head_branch = subprocess.run(
File "/srv/conda/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-remote', '--symref', '--', 'https://github.com/PHW290/PHW251_Fall2022', 'HEAD']' returned non-zero exit status 128.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/srv/conda/lib/python3.10/site-packages/nbgitpuller/handlers.py", line 87, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
File "/srv/conda/lib/python3.10/site-packages/nbgitpuller/pull.py", line 79, in __init__
    self.branch_name = self.resolve_default_branch()
File "/srv/conda/lib/python3.10/site-packages/nbgitpuller/pull.py", line 134, in resolve_default_branch
    raise ValueError(m)
ValueError: Problem accessing HEAD branch: https://github.com/PHW290/PHW251_Fall2022".   And when I try to ope github I get a 404- this is not the page you are looking for. I would not know how to retrieve WHERE-ARE-MY-FILES.txt" for R.

**Comment by balajialg** [comment]
@mnazneen Can you try accessing this URL - https://r.datahub.berkeley.edu/ and see if you can find WHERE-ARE-MY-FILES.txt?

**Comment by balajialg** [comment]
Closing this issue due to inactivity!
